name: an_lifecycle_hooks
description: "Provide an extension development toolkit for the flutter_hooks library for anlifecycle and an_viewmodel."
version: 2.2.0
homepage: https://github.com/aymtools/lifecycle_hooks/
issue_tracker: https://github.com/aymtools/lifecycle_hooks/issues

topics:
  - hooks-lifecycle
  - use-lifecycle
  - use-view-model
  - use-lifecycle-view-model

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  weak_collections: ^1.2.1
  flutter_hooks: ^0.19.0

  cancellable: ^2.2.2
  anlifecycle: ^3.1.4
  an_lifecycle_cancellable: ^2.3.1
  an_viewmodel: ^3.0.2

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
